### ISSUE TITLE
What is the Image size (MB) maximum supported and resolution .

### ISSUE THREAD

**Issue by kalkat** [daimajia/AndroidImageSlider#106]
Hello, I try to add two images to the slider but not works with images large than 500 kb. What is the maximum size of images?

Thanks

**Comment by daimajia** [comment]
This lib is using [Picasso](https://github.com/square/picasso/) to load images. I'm not queit sure if there is any restriction when loading image in Picasso.  

You can submit a issue in Picasso repository. 

If any one know on this issue, feel free to comment here.

**Comment by daimajia** [comment]
This issue will be discussed in #94
