### ISSUE TITLE
How to disable infinite scroll?

### ISSUE THREAD

**Issue by deltaguita** [daimajia/AndroidImageSlider#162]
Hi:

How to disable infinite scroll?
I hope slider :
  can't scroll to left  when position ==0  
  can't scroll to right when position == adapter .size-1

**Comment by rafatabosa** [comment]
Hi,

You can achieve this behavior by implementing the logic below on onPageSelected method.

private int previousPosition = 0;
    @Override
    public void onPageSelected(int position) {
        if(previousPosition == SLIDER_COUNT && position == 0) {
            slider.movePrevPosition();
            return;
        } else if(previousPosition == 0 && position == SLIDER_COUNT) {
            slider.moveNextPosition();;
            return;
        }
        previousPosition = position;
}

**Comment by dogauzun** [comment]
I have the same problem but could not understand the offered solution. Could anyone clarify?

Where should I implement this logic?

**Comment by arshak-tekticks** [comment]
Thanks rafatabosa

**Comment by anoopch** [comment]
Addd an OnPageChangeListener to the SliderLayout and implement the solution given by @rafatabosa 

```
mPhotoSliderLayout = (SliderLayout)findViewById(R.id.mPhotoSliderLayout );
final int SLIDER_COUNT = imagesProvider.getImages().size() - 1;
mPhotoSliderLayout.setPresetIndicator(SliderLayout.PresetIndicators.Right_Bottom);
mPhotoSliderLayout..stopAutoCycle();
mPhotoSliderLayout.setIndicatorVisibility(PagerIndicator.IndicatorVisibility.Invisible);
mPhotoSliderLayout.addOnPageChangeListener(
new ViewPagerEx.OnPageChangeListener() {
                        private int previousPosition = 0;
                        @Override
                        public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) { }

                        @Override
                        public void onPageSelected(int position) {
                            if (previousPosition == SLIDER_COUNT && position == 0) {
                                mPhotoSliderLayout.movePrevPosition();
                                return;
                            } else if (previousPosition == 0 && position == SLIDER_COUNT) {
                                mPhotoSliderLayout.moveNextPosition();
                                return;
                            }
                            previousPosition = position;
                        }

                        @Override
                        public void onPageScrollStateChanged(int state) { }
                    }
            );

```

**Comment by deltaguita** [comment]
thx!

**Comment by AungThiha** [comment]
it doesn't work when there's only two images.

Imagine the position is 0 and you move next. So the value of **previousPosition** is 0 and **position** is 1 which satisfies this condition "previousPosition == 0 && position == SLIDER_COUNT". So, it will go back to position 0 and you will never be able to swipe to position 1.
