### ISSUE TITLE
How to hide progress and stop scrolling

### ISSUE THREAD

**Issue by wakirin** [daimajia/AndroidImageSlider#18]
Hi, i have two questions:
1. How to stop scrolling when one image ? I use "sliderShow.stopAutoCycle();", but how to disable for user it?
2. I have problem when just one image in slider, problem with progress loading, he not hide if used "sliderShow.stopAutoCycle();".

And thank you for this great library.

**Comment by AdityaPathak-Infy** [comment]
Hi @daimajia 
I have used your library for image sliding and its working fine. So thanks for developing such a great library.
Actually now i am facing small problem in your library , my requirement is that i want to stop the sliding of photos when user start manually scrolling but when user stops and after the delay of 10 seconds ,the library should start automatic slide.

Please help me over this.. 
I am struggling over it from past two days. So any help would be highly appreciable.

Thanks in advance.

**Comment by amalkronz** [comment]
try this, it will stop the swiping and auto Cycle in slider, it's work for me
`if (imageCount < 2) {
            sliderShow.stopAutoCycle();
            sliderShow.setPagerTransformer(false, new BaseTransformer() {
                @Override
                protected void onTransform(View view, float v) {
                }
            });
           //TODO: disable indicator
}`
