### ISSUE TITLE
How to load the image from mobile directory?

### ISSUE THREAD

**Issue by waikchiu5** [daimajia/AndroidImageSlider#211]
I store some images in

> /storage/emulated/0/abc/

For example, there are only 3 file.
1.jpg
2.jpg
3.jpg

I tried to put in to Hashmap

```
url_maps.put("1","/storage/emulated/0/abc/1.jpg");
url_maps.put("1","/storage/emulated/0/abc/2.jpg");
url_maps.put("1","/storage/emulated/0/abc/3.jpg");
```

It cannot show the image?

**Comment by waikchiu5** [comment]
Oh, my mistake
DefaultSliderView image() need to pass File type

**Comment by nizzam** [comment]
@waikchiu5 How did u solve this ? Please explain.

**Comment by Forchapeatl** [comment]
Please how did you solve problem

**Comment by zeylevruntime** [comment]
you must get your file path like this
File fileImage = new File("/storage/emulated/0/Pictures/cropped2007392235.
HashMap<String,File> url_maps = new HashMap<String, File>();
url_maps.put("Big Bang Theory", fileImage);

**Comment by zeylevruntime** [comment]
you must get your file path like this
File fileImage = new File("/storage/emulated/0/Pictures/cropped2007392235.jpg
HashMap<String,File> url_maps = new HashMap<String, File>();
url_maps.put("Big Bang Theory", fileImage);
