### ISSUE TITLE
fragment implementation

### ISSUE THREAD

**Issue by yousofkakhki** [daimajia/AndroidImageSlider#216]
please tell me how to implement it in my fragment 
package info.androidhive.materialtabs.fragments;

import android.content.Context;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.daimajia.slider.library.Animations.DescriptionAnimation;
import com.daimajia.slider.library.SliderLayout;
import com.daimajia.slider.library.SliderTypes.BaseSliderView;
import com.daimajia.slider.library.SliderTypes.TextSliderView;

import java.util.HashMap;

import info.androidhive.materialtabs.R;
import info.androidhive.materialtabs.activity.MainActivity;

public class OneFragment extends Fragment{
    Context context;
    public OneFragment() {
        // Required empty public constructor

```
}

@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    context = getActivity();

}

@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container,
                         Bundle savedInstanceState) {
    // Inflate the layout for this fragment
    SliderLayout sliderShow = (SliderLayout) container.findViewById(R.id.slider);



    HashMap<String,Integer> file_maps = new HashMap<String, Integer>();
    file_maps.put("Hannibal",R.drawable.hannibal);
    file_maps.put("Big Bang Theory",R.drawable.bigbang);
    file_maps.put("House of Cards",R.drawable.house);
    file_maps.put("Game of Thrones", R.drawable.game_of_thrones);

    for(String name : file_maps.keySet()) {
        TextSliderView textSliderView = new TextSliderView(context);
        Log.v("null",String.valueOf(context==null));
        // initialize a SliderLayout
        textSliderView
                .description(name)
                .image(file_maps.get(name))
                .setScaleType(BaseSliderView.ScaleType.CenterCrop);

        sliderShow.addSlider(textSliderView);
    }

    sliderShow.setPresetTransformer(SliderLayout.Transformer.Fade);
    sliderShow.setPresetIndicator(SliderLayout.PresetIndicators.Center_Bottom);
    sliderShow.setCustomAnimation(new DescriptionAnimation());
    sliderShow.setDuration(500);

    return inflater.inflate(R.layout.fragment_one, container, false);


}
```

}
it gives me "Attempt to invoke virtual method 'void com.daimajia.slider.library.SliderLayout.addSlider(com.daimajia.slider.library.SliderTypes.BaseSliderView)' on a null object reference"

**Comment by AbrahamMC** [comment]
Im getting the same issue, does the library support fragments? Please give feedback :) I like how it works in simple activities but I also would like to use it on a fragment.

**Comment by AbrahamMC** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.daimajia.slider.library.SliderLayout.addSlider(com.daimajia.slider.library.SliderTypes.BaseSliderView)' on a null object reference

 public void startSlider(){
        Context contextSl = getActivity();
        //Set the slider for header images----------------------------------------------------------------------------------Abe Cruz
        url_maps = new HashMap<String, String>();
        url_maps.put("Hannibal", "http://static2.hypable.com/wp-content/uploads/2013/12/hannibal-season-2-release-date.jpg");
        url_maps.put("Big Bang Theory", "http://tvfiles.alphacoders.com/100/hdclearart-10.png");
        url_maps.put("House of Cards", "http://cdn3.nflximg.net/images/3093/2043093.jpg");
        url_maps.put("Game of Thrones", "http://images.boomsbeat.com/data/images/full/19640/game-of-thrones-season-4-jpg.jpg");

        for(String name : url_maps.keySet()){
            TextSliderView textSliderView = new TextSliderView(contextSl);
            // initialize a SliderLayout
            textSliderView
                    .description(name)
                    .image(url_maps.get(name))
                    .setScaleType(BaseSliderView.ScaleType.Fit)
                    .setOnSliderClickListener((BaseSliderView.OnSliderClickListener) contextSl);

            //add extra information
            textSliderView.bundle(new Bundle());
            textSliderView.getBundle().putString("extra",name);
            mSlider.addSlider(textSliderView);
        }
        mSlider.setPresetTransformer(SliderLayout.Transformer.FlipPage);
        mSlider.setPresetIndicator(SliderLayout.PresetIndicators.Center_Bottom);
        mSlider.setCustomAnimation(new DescriptionAnimation());
        mSlider.setDuration(4000);
        mSlider.addOnPageChangeListener((ViewPagerEx.OnPageChangeListener) contextSl);
        //Set the slider for header images----------------------------------------------------------------------------------Abe Cruz
    }

**Comment by androidninja11** [comment]
Do This In Fragment Worked Good For Me

textSliderView
                    .description(name)
                    .image(HashMapForLocalRes.get(name))
                    .setScaleType(BaseSliderView.ScaleType.Fit)
                    .setOnSliderClickListener(new BaseSliderView.OnSliderClickListener() {
                        @Override
                        public void onSliderClick(BaseSliderView slider) {
                        }
                    });
