### ISSUE TITLE
Demo has import unknow package

### ISSUE THREAD

**Issue by suntenday** [daimajia/AndroidImageSlider#226]
import com.daimajia.androidanimations.library.attention.StandUpAnimator;

have no StandUpAnimator.class in the project

in /AndroidImageSlider/src/com/daimajia/slider/demo/ChildAnimationExample.java

Line 46 , new StandUpAnimator().animate(descriptionLayout); need this class

**Comment by suntenday** [comment]
import https://github.com/daimajia/AndroidViewAnimations

**Comment by SmartCoded** [comment]
import https://github.com/daimajia/AndroidViewAnimations

**Comment by SmartCoded** [comment]
import https://github.com/daimajia/AndroidViewAnimations
