### ISSUE TITLE
Slider Streched on Tablet

### ISSUE THREAD

**Issue by cliffgr** [daimajia/AndroidImageSlider#24]
Any change to use Wrap_content on that?

<com.daimajia.slider.library.SliderLayout
        android:id="@+id/slider"
        android:layout_below="@+id/NavigationBar"
        android:layout_width="fill_parent"
        custom:pager_animation="Accordion"
        custom:auto_cycle="true"
        custom:indicator_visibility="visible"
        custom:pager_animation_span="1100"
        android:layout_height="wrap_content"/>

**Comment by crysan** [comment]
Super!

**Comment by mirajabi** [comment]
When I put on the height to wrap content not show anything slider to me and when I 200dp height again on the tablet is stretch , what should I do ??
