### ISSUE TITLE
Set default image if image from url not available

### ISSUE THREAD

**Issue by arickanjass** [daimajia/AndroidImageSlider#270]
Hello, is it possible to set default image to slider if image from url not available ? thank you

**Comment by quocthinh212** [comment]
You can use this code:
Creat imageview below the slider view and set background for this view.


              <ImageView
                android:id="@+id/headerBG"
                android:layout_width="match_parent"
                android:layout_height="300dp"
                android:scaleType="centerInside"
                android:contentDescription="@string/app_name"
                android:fitsSystemWindows="true"
                android:background="@drawable/mabg"
                android:alpha="1" />

            <com.daimajia.slider.library.SliderLayout
                android:id="@+id/slider"
                android:layout_width="match_parent"
                custom:pager_animation="Accordion"
                custom:auto_cycle="true"
                custom:indicator_visibility="visible"
                custom:pager_animation_span="1100"
                android:fitsSystemWindows="true"
                android:layout_height="300dp"/>

**Comment by UsmanGhauri** [comment]
Yes easy and simple

            textSliderView
                    .description(name)
                    .image(url_maps.get(name))
                    **.empty(R.drawable.ic_ejazah_placeholder)**
                    .setScaleType(BaseSliderView.ScaleType.Fit)
                    .setOnSliderClickListener(this);


the **.empty(Drawable Resource)** give a place hodler in that and **.error(Drawable Resource)** give an error image

**Comment by arickanjass** [comment]
thanks man . saved my day @UsmanGhauri

**Comment by panktisugandhi** [comment]
Its not working so please give me to the another solution
