### ISSUE TITLE
Resume swipe after user touches on image

### ISSUE THREAD

**Issue by RishavChudal** [daimajia/AndroidImageSlider#278]
I have getting an problem. Whenever i  click on any image while the layout is swiping, swiping stops and i have to resume it manually. How to solve this?

**Comment by pickeloe5** [comment]
Well I think this is a feature that was added so if the user wants to navigate the slideshow themselves, the autoswipe doesn't interrupt them. To disable this, you can use a custom slider layout class that extends SliderLayout and Overrides onInterceptTouchEvent with an empty function.

The class would look something like this

```
public class CustomSliderLayout extends SliderLayout {

    public CustomSliderLayout(Context context) {
        super(context);
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent e) {
        return false;
    }
}
```

Then you'd just use this class in your layout.

```
       <com.yourdomain.yourpackage.CustomSliderLayout
            android:id="@+id/explore_details_slider"
            android:layout_width="match_parent"
            android:layout_height="200dp"
            custom:indicator_visibility="invisible" />
```

**Comment by RishavChudal** [comment]
Thankyou so much sir. I will try that. I just wanted the layout to pause
when clicked otherwise i needed it to resume automatically. Thanks again !!

**Comment by nizzam** [comment]
I try implement your way @pickeloe5 , but got an error.

**Logcat:**
`android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.xdec.banner.CustomSliderLayout`


**MainActivity.java**
```
CustomSliderLayout sliderLayout;

private void setupViews() {
        sliderLayout = new CustomSliderLayout(this);
        sliderLayout = (CustomSliderLayout) findViewById(R.id.slider);
}
```

**activity_main.xml**
```
    <com.xdec.banner.CustomSliderLayout
        android:id="@+id/slider"
        android:layout_width="match_parent"
        android:layout_height="300dp"/>
```


Please help.

**Comment by RishavChudal** [comment]
@nizzam I think when you make a custom library from other's library, you just need to have/copy all the files/codes from the pre-built library in your custom class/classes and then you can edit as you like. After doing that, it shouldnt give any error in inflating your custom class. 
Hope I gave you a good suggestion.

**Comment by ajaydhadhal1111** [comment]
public void onSliderClick(BaseSliderView slider)
 {
        sliderLayout .startAutoCycle();
}
