### ISSUE TITLE
Android Studio Rendering Problems

### ISSUE THREAD

**Issue by metp** [daimajia/AndroidImageSlider#29]
Is it normal to get always rendering problems?
"Rendering Problems Missing styles. Is the correct theme chosen for this layout?  Use the Theme combo box above the layout to choose a different layout, or fix the theme style references."

The following classes could not be instantiated:
- com.daimajia.slider.library.SliderLayout (Open Class, Show Exception)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE  Exception Details java.lang.NullPointerException   at com.daimajia.slider.library.SliderLayout.<init>(SliderLayout.java:191)   at com.daimajia.slider.library.SliderLayout.<init>(SliderLayout.java:166)   at java.lang.reflect.Constructor.newInstance(Constructor.java:513)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:755)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:727)   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)   at android.view.LayoutInflater.inflate(LayoutInflater.java:373) Copy stack to clipboard  Failed to find style 'SliderStyle' in current theme (2 similar errors not shown)

**Comment by thandra** [comment]
Hi,
am trying the same thing everything is working fine,but the problem is if am having 5 images to display in the image slider.1st and second image are not displaying instead there is a black screen.what may be the issue please suggest me if any changes have to be implmented...
