### ISSUE TITLE
Coming blank in Fragment

### ISSUE THREAD

**Issue by pathanjalisrinivasan** [daimajia/AndroidImageSlider#298]
Hi, 
 I could able to implement it properly in activity class and it works perfectly fine but in fragment it just shows blank. 

My code in fragment 

               `slider = (SliderLayout)view.findViewById(R.id.slider);
                HashMap<String,String> url_maps = new HashMap<String, String>();
                url_maps.put("Hannibal", "http://static2.hypable.com/wp-content/uploads/2013/12/hannibal-season-2-release-date.jpg");
                url_maps.put("Big Bang Theory", "http://tvfiles.alphacoders.com/100/hdclearart-10.png");
                url_maps.put("House of Cards", "http://cdn3.nflximg.net/images/3093/2043093.jpg");
                url_maps.put("", "http://images.boomsbeat.com/data/images/full/19640/game-of-thrones-season-4-jpg.jpg");

                for(String name : url_maps.keySet())
                {
                    TextSliderView textSliderView = new TextSliderView(mContext);
                    textSliderView
                            .description(name)
                            .image(url_maps.get(name))
                            .setScaleType(BaseSliderView.ScaleType.Fit);
                    slider.addSlider(textSliderView);
                }`

Couldn't find the problem ?

**Comment by nizzam** [comment]
@pathanjalisrinivasan did u manage to fix it ?
