### ISSUE TITLE
Bitmap supporting

### ISSUE THREAD

**Issue by anonym24** [daimajia/AndroidImageSlider#306]
![screenshot_3](https://cloud.githubusercontent.com/assets/8851301/23578673/1c868ef0-00e5-11e7-8bba-d6817807bcd6.png)

Is there a possibility to load Bitmaps?

**Comment by JonathanRosado** [comment]
+1

**Comment by pmSven** [comment]
+1

**Comment by appsdev85** [comment]
Use File Instead 
`new File(images.get(i).path)`

**Comment by Forchapeatl** [comment]
> Use File Instead
> `new File(images.get(i).path)`

use like this
....
.image(new File(url_maps.get(name)))

**Comment by anonym24** [comment]
@HWSTS bitmap isn't on sdcard, don't suggest nosense

@Forchapeatl just copy the library and edit it to support bitmap
