### ISSUE TITLE
Close activity after last slide

### ISSUE THREAD

**Issue by Vol-i** [daimajia/AndroidImageSlider#31]
Hi,
I want to close the activity that holds the slider after last item on slider.
Is there a method or way that i can capture last slide is slided.

**Comment by AngryYogurt** [comment]
Hi, I have viewed 
https://github.com/daimajia/AndroidImageSlider/wiki/Slider-child-view-animation
but I still have no idea about how to get current slide position in DescriptionAnimation.

**Comment by massimobio** [comment]
You can add a OnPageChangeListener to the SliderLayout and be notified when the last slide is displayed https://github.com/daimajia/AndroidImageSlider/pull/100
