### ISSUE TITLE
How to change fix position of pagerIndicator (setPresetIndicator)

### ISSUE THREAD

**Issue by fongfuse** [daimajia/AndroidImageSlider#342]
How to change fix position of pagerIndicator (setPresetIndicator)

Yes , I knew it's can set  `.setPresetIndicator(SliderLayout.PresetIndicators.Center_Bottom);`

but I want to set my position

thanks!

**Comment by BlackCatXXF** [comment]
In layout,you can click PageIndicator to look its source code

**Comment by fongfuse** [comment]
@BlackCatXXF  Thanks!
