### ISSUE TITLE
TextlSliderViews are switching around in AsyncTask

### ISSUE THREAD

**Issue by Honeybyte** [daimajia/AndroidImageSlider#35]
I've a little problem. I must use an AsyncTask to make network operations. I get an image url in doInBackground for the slider but when I use the TextSliderView with the url in the onPostExecute methode the TextSliderViews are switching fast some times between them.

**Comment by knkmsht** [comment]
+1. Meet the similar situation.
When initialized, the slider will run once from -1 to 0 position.

Try this:
`slider.post(new Runnable() {
    @Override
    public void run() {
        ...slider.addSlider(sliderView);
    }
});`
