### ISSUE TITLE
How can i know when the slideshow was changed ?

### ISSUE THREAD

**Issue by selmanon** [daimajia/AndroidImageSlider#37]
Hi, 

I m using this amazing library, actually i need to know when the slideshow was changed.

Thank you

**Comment by eGorets** [comment]
littile hack. hope its helps

InfiniteViewPager infiniteViewPager = view.findViewById(com.daimajia.slider.library.R.id.daimajia_slider_viewpager)
  infiniteViewPager.setOnPageChangeListener(new ViewPagerEx.OnPageChangeListener() {
            @Override
            public void onPageScrolled(final int i, final float v, final int i2) {

            }

            @Override
            public void onPageSelected(final int i) {

            }

            @Override
            public void onPageScrollStateChanged(final int i) {
            }
        });

**Comment by massimobio** [comment]
@eGorets your solution works for detecting the page change, but unfortunately the selected dot on the PageIndicator is not longer updated.

**Comment by massimobio** [comment]
This issues has been addressed in the this pull request: https://github.com/daimajia/AndroidImageSlider/pull/100
You can now do 'addOnPageChangedListener' on the SliderLayout.
See demo app for and example.
