### ISSUE TITLE
Disable swipe when only one image ?

### ISSUE THREAD

**Issue by floating-cat** [daimajia/AndroidImageSlider#38]
How to disable swipe when only one image , or any workaround?

I know I can use `stopAutoCycle` to disable auto scrolling, but that's different.

Thanks.

**Comment by Klafe** [comment]
Hi! Is this issue resolved? Thank You!

**Comment by Taifuru** [comment]
@Klafe i think this library does not developing anymore

**Comment by daimajia** [comment]
@Taifuru Noop, still in developing, but just too busy on works.

**Comment by massimobio** [comment]
This issue is actively being discussed in https://github.com/daimajia/AndroidImageSlider/issues/82

**Comment by amalkronz** [comment]
try this, it will stop the swiping and auto Cycle in slider, it's work for me
`if (imageCount < 2) {
            sliderShow.stopAutoCycle();
            sliderShow.setPagerTransformer(false, new BaseTransformer() {
                @Override
                protected void onTransform(View view, float v) {
                }
            });
           //TODO: disable indicator
}`

**Comment by imi24** [comment]
create a boolean variable and setter in `SliderLayout.java`

    private boolean isDisableTouchEvent = true;
    public void setDisableTouchEvent(boolean disableTouchEvent) {
        isDisableTouchEvent = disableTouchEvent;
    }

and replace `onInterceptTouchEvent` function with below

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        if (isDisableTouchEvent)
            return true;
        else {
            int action = ev.getAction();
            switch (action) {
                case MotionEvent.ACTION_DOWN:
                    pauseAutoCycle();
                    break;
            }
            return false;
        }
    }


after that you can disable swipe with this 
    slider.setDisableTouchEvent(true);
