### ISSUE TITLE
Not working on API 28/ Android Pie

### ISSUE THREAD

**Issue by J6ey** [daimajia/AndroidImageSlider#411]
The slider doesn't load any images on this version.

**Comment by ibrha** [comment]
do you find the solution ?

**Comment by J6ey** [comment]
> do you find the solution ?

Nope.

**Comment by ibrha** [comment]
i use this its good  
 https://github.com/smarteist/android-image-slider
its work from 4.4 to 9.0 android

**Comment by tamtom** [comment]
You can check this library https://github.com/OpenSooq/Pluto 
1- no memory leaks 
2- not depending on any image loader

**Comment by J6ey** [comment]
So the problem was actually from Picasso and Glide themselves when loading network images.
And adding `android:usesCleartextTraffic="true"` to the manifest solved this issue.
