### ISSUE TITLE
OnPageChangeListener

### ISSUE THREAD

**Issue by pkliang** [daimajia/AndroidImageSlider#42]
Hi, 
Does it support listener like ViewPager.OnPageChangeListener?

**Comment by iloveaman** [comment]
//aman
    public void setOnPageChangeListener(OnPageChangeListener onPageChangeListener){
        if(onPageChangeListener!=null){
        	mViewPager.setOnPageChangeListener(onPageChangeListener);
        }
    }
    //aman

**Comment by iloveaman** [comment]
i added this method. But i the method onPageSelected(position) ,the position is not correct. For example ,it should be 1 when i scrolled the ViewPager from current position 0 to 1,but the   position beccame to 20522 ,such as.

**Comment by Frequencies** [comment]
Any news about this issue?

**Comment by devflow** [comment]
This issue need to edit onPageScrolled function in PagerIndicator class.

**Comment by MedoElkamaly** [comment]
i added the method to SliderLayout.java but it's not warking. this is my code



mDemoSlider.setOnPageChangeListener(new ViewPagerEx.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int i, float v, int i2) {
                Toast.makeText(getActivity().getApplicationContext(),
                        "x", Toast.LENGTH_SHORT)
                        .show();
            }

            @Override
            public void onPageSelected(int i) {
                Toast.makeText(getActivity().getApplicationContext(),
                        "x", Toast.LENGTH_SHORT)
                        .show();

            }

            @Override
            public void onPageScrollStateChanged(int i) {
                Toast.makeText(getActivity().getApplicationContext(),
                        "x", Toast.LENGTH_SHORT)
                        .show();
            }
        });

**Comment by devflow** [comment]
@MedoElkamaly The ViewPagerEx's onPageChangeListemer is using for pageindicator. so you need to make an OnChangeListener in PageIndicator.

**Comment by devflow** [comment]
```java
public class PagerIndicator extends LinearLayout implements ViewPagerEx.OnPageChangeListener{
        private ViewPagerEx.OnPageChangeListener onPageChangeListener;
        public ViewPagerEx.OnPageChangeListener getOnPageChangeListener() {
               return onPageChangeListener;
        }
        public void setOnPageChangeListener(ViewPagerEx.OnPageChangeListener onPageChangeListener) {
          this.onPageChangeListener = onPageChangeListener;
        }

        ....

        @Override
        public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
                if(mItemCount == 0){
                    return;
                }
                int n = position % mItemCount;
                setItemAsSelected(n - 1);
                if(getOnPageChangeListener() != null){
                      getOnPageChangeListener().onPageSelected(n);
                }

        }

```

and like this.
```java
 Slider.getPagerIndicator().setOnPageChangeListener(new ViewPagerEx.OnPageChangeListener() {});

```

**Comment by massimobio** [comment]
@devflow your solution works, I wish it was included in the library.

**Comment by MedoElkamaly** [comment]
It works :100: thanks @devflow :)

**Comment by massimobio** [comment]
This issues has been addressed in the latest pull request: https://github.com/daimajia/AndroidImageSlider/pull/100
You can now do `addOnPageChangeListener` on the SliderLayout

**Comment by daimajia** [comment]
Thanks @massimobio for this awesome PR. :-D
