### ISSUE TITLE
SliderLayout should stop animation when there is only one image

### ISSUE THREAD

**Issue by LOG-TAG** [daimajia/AndroidImageSlider#50]
```HashMap<String,Integer> file_maps = new HashMap<String, Integer>(); file_maps.put("Hannibal",R.drawable.ic_panorama_grey600_48dp);```

SliderLayout should stop animation slide when there is only one image or we need a method like 

``` 
mDemoSlider.setEnableslider(true);
``` 
or

```  
  mDemoSlider.setPresetTransformer(SliderLayout.Transformer.disable);
``` 

this is similar https://github.com/daimajia/AndroidImageSlider/issues/38  issue but slightly different !

**Comment by massimobio** [comment]
This issue is actively being discusse in https://github.com/daimajia/AndroidImageSlider/issues/82
