### ISSUE TITLE
Enable zooming for ImageView

### ISSUE THREAD

**Issue by adityathakar** [daimajia/AndroidImageSlider#61]
Hi @daimajia  
Thanks for the library. It is really useful. 
In my application, I need to enable zooming functionality for the ImageView in slider. 
I tried changing the default ImageView class in your library with TouchImageView class which provides the required zooming feature. 
But it seems that Picasso library is used for callbacks for success or error of Image load so I could not change the ImageView class there. 
Is there any other way I can implement zooming functionality ?

**Comment by ericntd** [comment]
how did you achieve that @adityathakar ? can you share :D

**Comment by adityathakar** [comment]
@ericn37 Hey mate, sorry for late reply
I used the below library for zooming. 
https://github.com/chrisbanes/PhotoView

**Comment by ericntd** [comment]
thanks @adityathakar

**Comment by SalvatoreAD** [comment]
Hi, how did you use the library PhotoView inside the slideshow?
