### ISSUE TITLE
.setCuurentPosition hangs when traversing backwards

### ISSUE THREAD

**Issue by nitin84india** [daimajia/AndroidImageSlider#63]
Hi, I found an issue when using setCurrentPosition method while traversing backwards. Suppose I am at slide no 1 and called .setCurrentPosition method to set current slide index to 5, it will work, but if I call .setCurrentPosition from 5th index to say 3rd then the application hangs. I'm getting the following error in doing so: 
E/dalvikvm﹕ Fatal spin-on-suspend, dumping threads

**Comment by kailash09dabhi** [comment]
Yes nitin is right. It hangs on backward selection.

**Comment by muratogat** [comment]
+1
This also indirectly causes nifty ANR states when switching between screens with Image Sliders and trying to set initial position to 0 while switching on their start. 
I have 5 images in the slider.

**Comment by praveenspark** [comment]
This issue is still there. 
Any fixes?

**Comment by anshulagarwal06** [comment]
I am also facing this issue.
Any solution for this?

**Comment by oalpayli** [comment]
I am also facing tooo. Can anybody help me?

**Comment by samira-badamestani** [comment]
i have this issue too.

**Comment by darwin2k** [comment]
same problem :/

**Comment by darwin2k** [comment]
this seems to be working for me:
Set the slider to last position and then call moveNextPosition() because of the infinite loop.

```
 profileSlider.setCurrentPosition(arrayLength, false);
 profileSlider.moveNextPosition();
```

**Comment by ubione88** [comment]
This work for me, thanks @darwin2k 

```
  if (sliderLayout.getCurrentPosition() > position) {
                    sliderLayout.setCurrentPosition( array.size() - 1, false);
                    sliderLayout.moveNextPosition();
                }
                sliderLayout.setCurrentPosition(position, false);
```

**Comment by zia-limemedia** [comment]
if (sliderLayout.getCurrentPosition() > position) {
                    sliderLayout.setCurrentPosition( array.size() - 1, false);
                    sliderLayout.moveNextPosition();
                }
                sliderLayout.setCurrentPosition(position, false);

not working for me.

**Comment by paakjis** [comment]
> This work for me, thanks @darwin2k
> 
> ```
>   if (sliderLayout.getCurrentPosition() > position) {
>                     sliderLayout.setCurrentPosition( array.size() - 1, false);
>                     sliderLayout.moveNextPosition();
>                 }
>                 sliderLayout.setCurrentPosition(position, false);
> ```

This doesn't freeze the app at least. But it doesn't load the images.
I changed the smooth loading to true, and it started loading them.
