### ISSUE TITLE
Delay duration ignored for first slide when activity first started

### ISSUE THREAD

**Issue by MarcRubio** [daimajia/AndroidImageSlider#70]
When you start the activity with the slider and if this is set to auto-cycle, the first image will slide to the next almost instantly even though a delay is set. The .setDuration() delay will work after this initial slide.

Apart from that well done, very nice library!

**Comment by sezya-kot** [comment]
Yep, I have a similar situation. Could you give advice how to solve this problem. Thanks a lot)

**Comment by 3lements** [comment]
Same here :)

**Comment by dharmeshvivacious** [comment]
I have also same Problem.:)

**Comment by cactis** [comment]
try this
```java
...
mSlider.setPresetTransformer(4);
mSlider.setDuration(8000);
mSlider.stopAutoCycle();
...
final Handler handler = new Handler();
handler.postDelayed(new Runnable() {
  @Override
  public void run() {
    mSlider.startAutoCycle();
  }
}, 5000);      
```

**Comment by andreyluiz** [comment]
I saw that the issue was fixed by the above commit. But for me, with version 1.1.5 it is not working. I had to implement the above solution to get this working. Anyone knows why?
