### ISSUE TITLE
Can I make it not cycle?

### ISSUE THREAD

**Issue by AngryYogurt** [daimajia/AndroidImageSlider#71]
I want to make the SliderLayout as a line instead of a circle. Is there any way to make it not cycle?

**Comment by daimajia** [comment]
Yeah, it support line, check the wiki

https://github.com/daimajia/AndroidImageSlider/wiki/Custom-Indicators

**Comment by AngryYogurt** [comment]
I mean cycle... not 'auto cycle'. Are you sure assigning 'mAutoCycle' to false can make it do nothing after I slide screen to left at the last image?

**Comment by daimajia** [comment]
Why not just use ViewPager ? http://developer.android.com/training/animation/screen-slide.html
