### ISSUE TITLE
remove the text description

### ISSUE THREAD

**Issue by jjhesk** [daimajia/AndroidImageSlider#78]
how do i remove the text descriptions?

**Comment by jjhesk** [comment]
fixed. I start using the defaultSliderView

**Comment by CNVGINFO** [comment]
public View getView() {
            View v = LayoutInflater.from(getContext()).inflate(com.daimajia.slider.library.R.layout.render_type_default,null);
            ImageView target = (ImageView)v.findViewById(com.daimajia.slider.library.R.id.daimajia_slider_image);
            TextView description = (TextView)v.findViewById(com.daimajia.slider.library.R.id.description);
            //description.setText(this.getDescription());
            bindEventAndShow(v, target);
            return v;
        }

**Comment by RameshbabuJaga** [comment]
using DefaultSliderView instead of TextSliderView hiding the text description.

**Comment by swarooplal** [comment]
DefaultSliderView defaultSliderView = new DefaultSliderView(MainActivity.this);
            defaultSliderView .image(Hash_file_maps.get(name))
                    .setScaleType(BaseSliderView.ScaleType.Fit)
                    .setOnSliderClickListener(this);
            sliderLayout.addSlider(defaultSliderView);

**Comment by NetdroidSunil** [comment]
Thanks , that's working fine.
