### ISSUE TITLE
Is there an explicit reason to require permissions?

### ISSUE THREAD

**Issue by shekibobo** [daimajia/AndroidImageSlider#9]
It's not clearly explained in the documentation why either the `INTERNET` or `READ_EXTERNAL_STORAGE` permissions are required. Is it possible to use this library with either one and not the other? Generally, permissions shouldn't be used unless absolutely necessary, and everyone (developers and users) should know exactly why and how those permissions are used. It would be great if there was an explanation behind the need for either or both permissions when using this library. What features are gained from using them, and are either of them optional depending on usage? Thanks.

**Comment by BaranBerk** [comment]
I don't want to cache any photo but I am getting them from internet is it possible remove these permissions
