### ISSUE TITLE
How to disable drawable black color on indicator???

### ISSUE THREAD

**Issue by best2010** [daimajia/AndroidImageSlider#91]
![bb](https://cloud.githubusercontent.com/assets/7048559/7248225/59389fba-e83b-11e4-834e-699d5cd33796.png)

I want disable this black background but i can't ...
help me to disable it.

**Comment by massimobio** [comment]
Sounds like you are using TextSliderView instead of DefaultSliderView

**Comment by daimajia** [comment]
Make sure that you have changed the default setting. Please check the example code and [wiki](https://github.com/daimajia/AndroidImageSlider/wiki).

**Comment by best2010** [comment]
I got it.
Thank you
