### ISSUE TITLE
Hey, guys, I need your help.

### ISSUE THREAD

**Issue by daimajia** [daimajia/AndroidImageSlider#95]
I'm the author of this library, and the authors of some [other libraries](https://github.com/daimajia).  

Most of them looks pretty popular, I can receive many issues and pull request everyday. The problem is I can not hanlde each of them in time, cause I have started a startup with my friends in the past few months, startup is a really hard time, I can not devote all my time to open source right now.

So, I really need  your help, I need some collaborators to participate in this project or others.  

If you would like to be one of the collaborator, please feel free to comment below.

**Comment by Exlsunshine** [comment]
I am very willing to help you and contribute codes for your awesome library, but I am not familiar with the process about the cooperation at Github, so how can I help with these libraries specifically? Is there any instructions? : )

**Comment by daimajia** [comment]
@Exlsunshine Great. I will add you to be a collaborator of this project. You will own the following authorities:

### Authories
- push code to this repo directly
- merge pull request directly
- close issue direcly

At the same time
### Responsibility
- handle the issues
- handle the feature request
- make code review when get a pull request

### Process
When you want to handle a issue, the process should be like the following:
- create a branch
- commit and push code to the new branch
- when make sure that is stable, send a pull request. 
- collaborators will make code review and comment on the pull request.
- merge or close.

Make sure that don't push code to master branch directly though you have authority on that 

Make sure that the master branch is always statble version

**Comment by wangxin05** [comment]
Hi, very thanks daimajia, expect more late participation, contribution and cooperation.

**Comment by daimajia** [comment]
@wangxin05 Welcome to join this project. :-D

**Comment by be4you** [comment]
Awesome library. Awesome community.

**Comment by zhouqiangWang** [comment]
hello, I am looking forward to participating in these cool projects.
*Be open source, be nice to the world~*

**Comment by daimajia** [comment]
@zhouqiangWang @be4you Welcome to join! Please make sure that you can obey the Git and GitHub workflow.

**Comment by LyndonChin** [comment]
@daimajia I really appreciate this opportunity to participate in the contribution. So please allow me to try my best to help you.

**Comment by daimajia** [comment]
@LyndonChin  Great! Welcome to join this project.

**Comment by daimajia** [comment]
@LyndonChin I have added you into collaborators list. :-D

**Comment by LyndonChin** [comment]
@daimajia Thank you so much !

**Comment by jalvarado91** [comment]
@daimajia I'm willing to contribute here too. It looks like we have a nice group of collaborators going.

**Comment by daimajia** [comment]
@jalvarado91 Great!  I have added you to collaborator list. Check it.

**Comment by tunjos** [comment]
HI @daimajia ,
I'd love to help. I also found a fix for those complaining about resizing and out of memory issues.
Let me know.

**Comment by daimajia** [comment]
@tunjos Awesome! Let me add you to the collaborator list. Make sure you have read the Authorities and Responsibilities carefully. :-D

**Comment by tunjos** [comment]
Sure. Done :)

**Comment by kavyaub** [comment]
@tunjos I was searching if you posted the solution for the out of memory issue and could not find it. Could you please provide the solution or a link to the solution..?
Thanks in advance.

**Comment by tunjos** [comment]
@kavyaub You can find the closed **pr** here https://github.com/daimajia/AndroidImageSlider/pull/125.
I think the **resize(int, int);** method was key to preventing **oom**s for large bitmaps.
Best!

**Comment by kavyaub** [comment]
@tunjos Thanks a lot. I'll look into it.
